name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SirFaizdat
website: http://sirfaizdat.github.io/Prison/
main: me.sirfaizdat.prison.Prison
softdepend: [Vault, WorldEdit]
commands:
  prison:
    description: Commands to manage Prison itself.
    usage: /<command>